name: Codecov

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test
        uses: actions/checkout@v3
      - name: Build and Test
        run: xcodebuild test -scheme 'ZMarkupParser' -enableCodeCoverage YES -resultBundlePath './scripts/TestResult.xcresult' -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1' build test | xcpretty
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          xcode: true
          xcode_archive_path: './scripts/TestResult.xcresult'
 
